import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Helper',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex gap-5 bg-gradient-to-r min-h-screen from-[#303030] to-[#1e1e1e] p-5'>
          <Navbar />
          {children}
        </div>
        </body>
    </html>
  )
}
