import Image from 'next/image'

export const metadata = {
    title: 'Tailwind Constructor',
    description: 'Generated by create next app',
  }

export default function Page() {
  return (
    <main className="flex flex-col">
      
    </main>
  )
}
